name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and test against Neo4j 5
    runs-on: ubuntu-latest
    env:
      NEO4J_OGM_NEO4J_ACCEPT_AND_USE_COMMERCIAL_EDITION: yes
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Run Maven build
        run: >
          ./mvnw --no-transfer-progress clean verify
